// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXN5RGSjqoNjr-H4M7jxATvXsyTgoipW4',
    appId: '1:156728441334:web:6fcdf06f5e92e1866aefd7',
    messagingSenderId: '156728441334',
    projectId: 'chatapp-4330f',
    authDomain: 'chatapp-4330f.firebaseapp.com',
    storageBucket: 'chatapp-4330f.appspot.com',
    measurementId: 'G-T8D47M8PZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD59pMeDig9UDK-j1RMRL71PQG-MadF1G4',
    appId: '1:156728441334:android:86cf373ac09bfdb06aefd7',
    messagingSenderId: '156728441334',
    projectId: 'chatapp-4330f',
    storageBucket: 'chatapp-4330f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0YaAHrSDLiNCUtJFHThgF1b0N7J7Ge3Y',
    appId: '1:156728441334:ios:00ec3f522c73b6d56aefd7',
    messagingSenderId: '156728441334',
    projectId: 'chatapp-4330f',
    storageBucket: 'chatapp-4330f.appspot.com',
    iosClientId: '156728441334-0sil78fte9tklihvpmnnjb4dk6jln4i5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0YaAHrSDLiNCUtJFHThgF1b0N7J7Ge3Y',
    appId: '1:156728441334:ios:7811a1ad2b210b016aefd7',
    messagingSenderId: '156728441334',
    projectId: 'chatapp-4330f',
    storageBucket: 'chatapp-4330f.appspot.com',
    iosClientId: '156728441334-u2q8rtaejnon9a52771kdg6seodhjo2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
